version: 2
jobs:
  build:
    working_directory: ~/App
    docker:
      - image: maven:3.3.9-jdk-8
    steps:
      - checkout
      - run:
          name: Testing
          command: mvn test
      - run:
          name: Show results
          command: cat target/surefire-reports/*.txt
