version: 2
jobs:
  build:
    working_directory: ~/App
    docker:
      - image: beevelop/android:latest
    branches:
      ignore:
        - master
    steps:
      - restore_cache:
          key: projectname-{{ .Branch }}
      - checkout
      - run:
          name: Testing
          command: ./gradlew test
      - save_cache:
          key: projectname-{{ .Branch }}
          paths:
            - "~/.cache"
      - store_test_results:
          path: app/build/test-results/testDebugUnitTest
      - store_test_results:
          path: app/build/test-results/testReleaseUnitTest