version: 2
jobs:
  build:
    working_directory: ~/App
    docker:
      - image: java:8
    steps:
      - checkout
      - run:
          name: Compile
          command: mkdir bin && cd src && javac -d ../bin/ -cp ".:..:../lib/hamcrest-core-1.3.jar:../lib/junit-4.12.jar" main/**/*.java ; cd ..
      - run:
          name: Testing
          command: cd bin && java -cp .:../lib/hamcrest-core-1.3.jar:../lib/junit-4.12.jar main.test.SuiteTester > result.txt ; cd ..
      - run:
          name: Show Result
          command: cd bin && cat result.txt
      - run:
          name: Check Failure
          command: exit $(grep -o 'FAIL' bin/result.txt | wc -l)

# New Folder
# mkdir bin && cd src && javac -d ../bin/ -cp ".:..:../lib/hamcrest-core-1.3.jar:../lib/junit-4.12.jar" main/**/*.java ; cd ..
# cd bin && java -cp .:../lib/hamcrest-core-1.3.jar:../lib/junit-4.12.jar main.test.SuiteTester > result.txt ; cd ..

# Root Folder
# javac -d . -cp ".:lib/hamcrest-core-1.3.jar:lib/junit-4.12.jar" src/main/**/*.java
# java -cp .:lib/hamcrest-core-1.3.jar:lib/junit-4.12.jar main.test.SuiteTester > result.txt
