version: 2
jobs:
  build:
    working_directory: ~/App
    docker:
      - image: gradle:3.4.1-jre8
    steps:
      - checkout
      - run:
          name: Testing
          command: mvn test
      - store_test_results:
                path: build/test-results/junit-platform