version: 2
jobs:
  build:
    working_directory: ~/App
    docker:
      - image: jacekmarchwicki/android:java7-8
    branches:
      ignore:
        - master
    steps:
      - setup_remote_docker
      - run: |
          export GRADLE_USER_HOME="$(pwd)/.gradle"
          export ANDROID_HOME="$(pwd)/.android"
      - checkout
      - run:
          name: Clean
          command: ./gradlew clean
      - run:
          name: Testing
          command: ./gradlew test
      - store_test_results:
          path: app/build/test-results/testDebugUnitTest
      - store_test_results:
          path: app/build/test-results/testReleaseUnitTest