version: 2
jobs:
  build:
    working_directory: ~/App
    docker:
      - image: jacekmarchwicki/android:java7-8
    branches:
      ignore:
        - master
    steps:
      - restore_cache:
          key: projectname-{{ .Branch }}
      - run:
          name: Set ENV
          command: export GRADLE_USER_HOME="$(pwd)/.gradle" && export ANDROID_HOME="$(pwd)/.android"
      - checkout
      - run:
          name: Testing
          command: ./gradlew test
      - save_cache:
          key: projectname-{{ .Branch }}
          paths:
            - "~/.cache"
      - store_test_results:
          path: app/build/test-results/testDebugUnitTest
      - store_test_results:
          path: app/build/test-results/testReleaseUnitTest