version: 2
jobs:
  build:
    working_directory: ~/App
    docker:
      - image: java:8
    steps:
      - checkout
      - run: mkdir bin
      - run: cd src
      - run:
          name: Compile
          command: javac -d ../bin/ -cp ".:..:../lib/hamcrest-core-1.3.jar:../lib/junit-4.12.jar" main/**/*.java
      - run: cd ..
      - run:
          name: Testing
          command: cd bin && java -cp .:../lib/hamcrest-core-1.3.jar:../lib/junit-4.12.jar main.test.SuiteTester > result.txt ; cd ..
      - run:
          name: Show Result
          command: cat result.txt

# cd src && javac -d ../bin/ -cp ".:..:../lib/hamcrest-core-1.3.jar:../lib/junit-4.12.jar" main/**/*.java && cd ..
# cd bin && java -cp .:../lib/hamcrest-core-1.3.jar:../lib/junit-4.12.jar main.test.SuiteTester > result.txt && cd ..
