version: 2
jobs:
  build:
    working_directory: ~/App
    docker:
      - image: jacekmarchwicki/android:java7-8
        environment:
          GRADLE_USER_HOME="$(pwd)/.gradle"
          ANDROID_HOME="$(pwd)/.android"
    branches:
      ignore:
        - master
    steps:
      - checkout
      - run:
          name: Testing
          command: ./gradlew test
      - store_test_results:
          path: app/build/test-results/testDebugUnitTest
      - store_test_results:
          path: app/build/test-results/testReleaseUnitTest